name: Flutter Windows Build

on:
  push:
    branches: [ windows-build ]
  pull_request:

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.x'  # Change to your Flutter version if needed

      - name: Enable Windows Desktop support
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Windows App
        run: flutter build windows

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-app
          path: build/
